apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: test-chat-7 
  janus-idp.io/tekton: test-chat-7
  backstage.io/kubernetes-id: test-chat-7
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: test-chat-7
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml